apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-production
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-ui-production-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-production-secret
    namespace: ui
---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-production
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-ecos-production-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-production-secret
    namespace: ecos
---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-production
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-apps-production-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-production-secret
    namespace: apps
---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-production
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-users-production-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-production-secret
    namespace: users

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-production
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-subs-production-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-production-secret
    namespace: subscriptions