apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscriptions
  labels:
    app.kubernetes.io/name: subscriptions
    app.kubernetes.io/instance: subscriptions
    app.kubernetes.io/component: service