apiVersion: v1
kind: Service
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/instance: apps
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: nathan_tinius
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: TARGET_PORT
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: apps
    app.kubernetes.io/instance: apps
    app.kubernetes.io/component: service