apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: nathan_tinius
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: TARGET_PORT
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/component: service