apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecos
  labels:
    app.kubernetes.io/created-by: nathan_tinius
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ecos
      app.kubernetes.io/instance: ecos
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ecos
        app.kubernetes.io/instance: ecos
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: nathan_tinius
        fargate: 'yes'
    spec:
      imagePullSecrets:
        - name: ac-aws-docker-key
      serviceAccountName: ecos
      containers:
        - name: ecos
          envFrom:
            - configMapRef:
                name: ecos
            - secretRef:
                name: doppler-production-secret
          image: "ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/TAG:Prod-v0.0.22"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: PORT
              protocol: TCP
          resources:
            limits:
              memory: 5G
            requests:
              cpu: '2'
              memory: 5G
