apiVersion: v1
kind: Service
metadata:
  name: ecos
  labels:
    app.kubernetes.io/name: ecos
    app.kubernetes.io/instance: ecos
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: nathan_tinius
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: PORT
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ecos
    app.kubernetes.io/instance: ecos
    app.kubernetes.io/component: service